name: semgrep

on:
  pull_request_target:
  merge_group:

  push:
    branches: [main]

  schedule:
    - cron: '30 0 1,15 * *'

jobs:
  scan:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@main
      - name: Run Semgrep to check for vulnerabilities
        run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_TOKEN }}
